blank_issues_enabled: true
contact_links:
  - name: Getting started
    url: https://github.com/qualersoft/robotframework-kolib/wiki
    about: Please have a look here first.
  - name: Getting help
    url: https://github.com/qualersoft/robotframework-kolib/discussions/categories/q-a
    about: Still not what you need? Have a look in our discussions Q&A
  - name: Search existing issues
    url: https://github.com/qualersoft/robotframework-kolib/issues
    about: If the wiki wasn't helpfull, please check for existing issues.
  - name: Talk with us
    url: https://github.com/qualersoft/robotframework-kolib/discussions
    about: Maybe also this may be interesting
