package de.qualersoft.robotframework.dummypack

import de.qualersoft.robotframework.library.SpringLibMarker
import org.springframework.boot.context.properties.ConfigurationPropertiesScan
import org.springframework.boot.context.properties.EnableConfigurationProperties

@EnableConfigurationProperties
@ConfigurationPropertiesScan
@SpringLibMarker
interface DummyMarker
